### ISSUE TITLE
Assignment 4 feedback

### ISSUE THREAD

**Issue by JJuOn** [choi5798/2019-Node.js-Study#1]
문제의 조건은 input.txt에서 두 수와 연산자를 받아와 사칙연산을 진행하고 output.txt에 출력하는 것이었습니다.  
제출한 파일에서는 output.txt을 쓰는 부분이 없습니다.  (힌트: fs.writeFile)  
또한. fs.readFile의 callback함수를 async 함수로 사용했는데, 
await과 함께 사용하기 위해서는 await 다음에 올 함수가 resolve처럼 Promise 객체를 반환해야 합니다.

**Comment by choi5798** [comment]
수정 했습니다
